jdbc_driver=com.mysql.jdbc.Driver
jdbc_url=jdbc:mysql://localhost:3306/test
jdbc_user=root
jdbc_password=root

#mybatis生成器
entity=com.yf.entity
dao=com.yf.model.mapper

#逆向工程(mapping)
tableName=t_bank
domainObjectName=Bank

